name: calender_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  menstrual_cycle_widget: ^1.1.0
  syncfusion_flutter_gauges: ^27.1.57
  intl: ^0.19.0
  timezone: ^0.10.0
  table_calendar: ^3.1.2
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.0.13
  fl_chart: ^0.69.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  hive_flutter: ^1.1.0

#  flutter_local_notifications: ^17.2.4
#  sqflite: ^2.4.0
#  path_provider: ^2.1.5
#  uuid: ^4.5.1
#  webview_flutter: ^4.10.0
#  flutter_secure_storage: ^4.2.1
#



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg.jpg
    - assets/emoji/
    - assets/drink/
    - assets/intercourse/
    - assets/symptoms/
    - assets/fluid/
    - assets/head/
    - assets/abdomen/
    - assets/body/
    - assets/cervix/
    - assets/ovulation/
    - assets/icons/
    - assets/self_care/
    - assets/phases/
    - assets/mental/
    - assets/partner_mode/
    - assets/pregnancy/
    - assets/Chat.svg


    #    - assets/emoji/
#    - assets/drink/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
