name: calendar_app
description: "Periods and Ovulation Tracking App."
publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^28.1.36
  confetti: ^0.8.0
  timezone: ^0.10.0
  table_calendar: ^3.1.2
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.0.13
  fl_chart: ^0.70.0
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.42
  uuid: ^4.5.1
  google_sign_in: ^6.2.1
  share_plus: ^10.1.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  pdf: ^3.11.1
  local_auth: ^2.3.0
  url_launcher: ^6.3.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2
  image_picker: ^1.1.2
  flutter_email_sender: ^7.0.0
  google_mobile_ads: ^5.3.1
  firebase_analytics: ^11.4.4
  vibration: ^3.1.3
  #  open_settings: ^2.0.2
  #  android_intent_plus: ^5.3.0
  app_settings: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
    - assets/bg.jpg
    - assets/emoji/
    - assets/drink/
    - assets/intercourse/
    - assets/fluid/
    - assets/head/
    - assets/abdomen/
    - assets/body/
    - assets/cervix/
    - assets/ovulation/
    - assets/icons/
    - assets/self_care/
    - assets/phases/
    - assets/mental/
    - assets/partner_mode/
    - assets/pregnancy/
    - assets/chat.png
    - assets/kegel/
    - assets/pets/
    - assets/kegel/audio/


